[package]
name = "naga-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "CLI for the naga shader translator and validator. Part of the wgpu project"
repository.workspace = true
keywords = ["shader", "SPIR-V", "GLSL", "MSL"]
license.workspace = true

# Override the workspace's `rust-version` key. Firefox uses `cargo vendor` to
# copy the crates it actually uses out of the workspace, so it's meaningful for
# them to have less restrictive MSRVs individually than the workspace as a
# whole, if their code permits. See `../README.md` for details.
rust-version = "1.76"

[[bin]]
name = "naga"
path = "src/bin/naga.rs"
# This _must_ be false, as this conflicts with `naga`'s docs.
#
# See https://github.com/gfx-rs/wgpu/issues/4997
doc = false
test = false

[dependencies]
naga = { workspace = true, features = [
    "wgsl-in",
    "wgsl-out",
    "glsl-in",
    "glsl-out",
    "spv-in",
    "spv-out",
    "msl-out",
    "hlsl-out",
    "dot-out",
    "serialize",
    "deserialize",
    "termcolor",
    "stderr",
    "fs",
] }

bincode = { workspace = true, features = ["serde"] }
codespan-reporting = { workspace = true, default-features = false, features = [
    "std",
    "termcolor",
] }
env_logger.workspace = true
argh.workspace = true
anyhow = { workspace = true, features = ["std"] }
log.workspace = true
