[package]
name = "wgpu-xtask"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
publish = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    # Added by xshell
    'cfg(trick_rust_analyzer_into_highlighting_interpolated_bits)',
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# The dependencies in this config have no transitive dependencies.
anyhow.workspace = true
env_logger.workspace = true
regex-lite.workspace = true
log.workspace = true
pico-args.workspace = true
xshell.workspace = true
