name: CTS

on:
  pull_request:
    types: [labeled, opened, synchronize]
  schedule:
    - cron: "33 2 * * *"
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: false
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  MSRV: "1.88"

jobs:
  cts:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows
          - name: Windows x86_64
            os: windows-2022
            target: x86_64-pc-windows-msvc
            backend: dx12

          # Mac
          - name: Mac aarch64
            os: macos-14
            target: x86_64-apple-darwin
            backend: metal

          # Linux
          - name: Linux x86_64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            backend: vulkan

    name: CTS ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Install Repo MSRV toolchain
        run: |
          rustup toolchain install ${{ env.MSRV }} --no-self-update --profile=minimal --target ${{ matrix.target }} --component llvm-tools
          rustup override set ${{ env.MSRV }}
          cargo -V

      - name: Install `cargo-llvm-cov`
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v2-rust # Increment version for cache busting
          cache-directories: cts

      # We enable line numbers for panics, but that's it
      - name: disable debug
        shell: bash
        run: |
          mkdir -p .cargo
          cat <<EOF >> .cargo/config.toml
          [profile.dev]
          debug = "line-tables-only"
          EOF

      - name: (Windows) Install DXC
        if: matrix.os == 'windows-2022'
        uses: ./.github/actions/install-dxc

      - name: (Windows) Install WARP
        if: matrix.os == 'windows-2022'
        uses: ./.github/actions/install-warp
        with:
          target-dirs: "target/llvm-cov-target/debug"

      - name: (Linux) Install Mesa
        if: matrix.os == 'ubuntu-24.04'
        uses: ./.github/actions/install-mesa

      - name: run CTS
        shell: bash
        run: cargo xtask cts --llvm-cov --backend ${{ matrix.backend }}

      - name: Generate coverage report
        id: coverage
        shell: bash
        continue-on-error: true
        run: |
          set -e

          cargo llvm-cov report --lcov --output-path lcov.info

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        if: steps.coverage.outcome == 'success'
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
